<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hex_ros_demo_composite</name>
  <version>0.0.0</version>
  <description>Composite impedance control demo for Maver X4 and dual Firefly Y6 robots</description>
  <maintainer email="thetaigon@qq.com">taigong26</maintainer>
  <license>Apache-2.0</license>

  <exec_depend condition="$ROS_VERSION == 2">launch</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">launch_ros</exec_depend>
  <exec_depend>hex_ros_demo_arm_impedance</exec_depend>
  <exec_depend>hex_ros_demo_chassis_impedance</exec_depend>
  <exec_depend>hex_ros_robot_arm</exec_depend>
  <exec_depend>hex_ros_robot_chassis</exec_depend>
  <exec_depend>hex_ros_teleop_joystick</exec_depend>
  <exec_depend>hex_ros_teleop_keyboard</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <export>
    <build_type condition="$ROS_VERSION == 2">ament_python</build_type>
  </export>
</package>
